### ISSUE TITLE
loader does not export the module

### ISSUE THREAD

**Issue by Fuzzyma** [webpack-contrib/exports-loader#18]
I use the lib [js-aruco](https://github.com/jcmellado/js-aruco) which is browser only. Thats why I try to shim that lib. I do it this way:

```js
module.exports = require('exports-loader?CV!../js-aruco/src/cv.js')
```

In the bundle I can see the libraray included - but the `module.exports = CV` is missing.
However - a similar case is working:

```js
module.exports = require('imports-loader?CV=./cv.js!exports-loader?AR!../js-aruco/src/aruco.js')
```

Here I can see the export. Ofc this code fails because it requires CV do be loaded correctly which is not the case.

I am using webpack v3

// EDIT: When requireing the module directly from my app `require('./modules/cv.js')` it exports the module. However cv still cant see ar because its put twice in the bundle. One time with export and one time without.

It looks like the export loader is simply not executed

**Comment by evilebottnawi** [comment]
Fixed in the master
