### ISSUE TITLE
Get 'Uncaught ReferenceError: exports is not defined' when using in webpack 4.6.0

### ISSUE THREAD

**Issue by Fuji-sunny** [webpack-contrib/exports-loader#24]
* Operating System: MacOS 10.13.3
* Node Version: 10.0.0
* NPM Version: 5.6.0
* webpack Version: 4.6.0
* exports-loader Version: 0.7.0

This issue is for a: 

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

```js
  module: {
       rules: [{
          test: '/\.js$/',
          loader: 'exports-loader'
       }]
  }
```

```js
  let main = new Vue();
  export default main;
  exports['main'] = main;  // this statement comes an error called "Uncaught ReferenceError: exports is not defined"
```

### Expected Behavior

'main' can be a global variable in the html.

### Actual Behavior

An error occurs when executing ' exports['main'] = main; ',
![image](https://user-images.githubusercontent.com/7186494/39610661-8a74f7aa-4f84-11e8-998f-0abc7942714e.png)

### How Do We Reproduce?

Set webpack's module like the above shows.

**Comment by LukeTully** [comment]
@Fuji-sunny Ran into the same problem, and addressed it in my fork https://github.com/LukeTully/exports-loader/blob/master/lib/index.js

It's the start of a more robust change to use es6 export syntax.
