### ISSUE TITLE
Cannot use with expose loader. Invalid options error even though options are valid.

### ISSUE THREAD

**Issue by Spence-S** [webpack-contrib/exports-loader#51]
- Operating System: MacOS Catalina 10.15.5
- Node Version: 12.18.2
- NPM Version: 6.14.5
- webpack Version: 4.43.0 
- webpack-cli version: 3.3.12 
- exports-loader Version: 1.1.0

### Expected Behavior

I expected a valid build and export of the module.

### Actual Behavior

Validation Error: 
```
ValidationError: Invalid options object. Exports Loader has been initialized using an options object that does not match the API schema.
 - options misses the property 'exports'. Should be:
   non-empty string | object { name, syntax?, alias? } | [non-empty string | object { name, syntax?, alias? }, ...] (should not have fewer than 1 item)
```

It is clear I have the options in the config.

### Code

```js
{
...
  module: {
    rules: [
      {
        test: path.resolve(__dirname, 'assets/public/js/templates.js'),
        use: [
          {
             loader: 'expose-loader',
             options: {
               exposes: 'templates'
             }
           },
          {
            loader: 'exports-loader',
            options: {
              type: 'commonjs',
              exports: 'single templates'
            }
          },
        ]
      }
    ]
  }
...
}
```

templates.js is a file with a single variable `templates`. I want webpack to add the exports code `module.exports = templates;` then expose that variable to the global scope so I can access `window.templates`. 

### How Do We Reproduce?

Simply use expose loader with exports loader. 

Also note that exports loader works as expected when used by itself without expose-loader.

**Comment by evilebottnawi** [comment]
Can't reproduce, works fine, please create reproducible test repo

**Comment by Spence-S** [comment]
thanks for the response @evilebottnawi - I decided to use a different method to load that module so I no longer need this. Not sure how reproducible it is in complex configurations. Going to close.
