### ISSUE TITLE
Becomes incompatible with es6-promise

### ISSUE THREAD

**Issue by andrenerd** [webpack-contrib/exports-loader#53]
- Operating System: MacOs
- Node Version: 13+
- NPM Version: 6.14.4
- webpack Version: 4.42.1
- exports-loader Version: 1.0.0+

### Expected Behavior

webpack: compiled successfully message.

### Actual Behavior

webpack: es6-promise throws an error. attached the screenshot.

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

import  "whatwg-fetch";

```js
// additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?

use webpack with the next modules:
    "whatwg-fetch": "latest"
    "es6-promise": "^4.2.8",
    "es6-promise-loader": "^1.0.2",
    "exports-loader": "1.0.0",

the issue comes up when any "fetch" related module imported, if export-loader v1.0.0+ installed. there have been no issues with previous ones.

![Screen Shot 2020-07-27 at 03 41 29](https://user-images.githubusercontent.com/3892914/88496437-68aa9600-cfbd-11ea-8efd-215f72e65be3.png)

**Comment by evilebottnawi** [comment]
You have invalid options, without configuration I can't help
