### ISSUE TITLE
this.getOptions is not a function

### ISSUE THREAD

**Issue by Steve229** [webpack-contrib/exports-loader#59]
Getting the following error:

Module build failed (from ./node_modules/exports-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/home/ssoloski/talon-ng/talon/node_modules/exports-loader/dist/index.js:23:24)
 @ ./app/javascript/packs/application.js 10:0-42

**Comment by cap-Bernardito** [comment]
Can't reproduce the error. Please create issue using issue template and provide a minimally reproducible test repo. After that I will reopen this issue.

**Comment by alexander-akait** [comment]
You need webpack v5 to use this loader, run `npm ls webpack`

**Comment by Steve229** [comment]
That’s prolly what it is... this is happening with a Rails Webpack build,
so it’s probably using an older version of Webpack.

Close the issue, and thanks for the info.

Steve
